### ISSUE TITLE
Formatting is broken

### ISSUE THREAD

**Issue by chrisrossi** [carlospalol/money#18]
Using Python 2.7.11, money 1.2.1, Babel 2.3.3:
~~~
>>> from money import Money
>>> Money('10', 'USD')
USD 10
>>> Money('10', 'USD').format()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/chris/proj/move/carts/eggs/money-1.2.1-py2.7.egg/money/money.py", line 249, in format
    pattern = babel.numbers.parse_pattern(pattern)
  File "/home/chris/proj/move/carts/eggs/Babel-2.3.3-py2.7.egg/babel/numbers.py", line 491, in parse_pattern
    if ';' in pattern:
TypeError: argument of type 'NoneType' is not iterable
>>> Money('10', 'USD').format('en_US')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/chris/proj/move/carts/eggs/money-1.2.1-py2.7.egg/money/money.py", line 249, in format
    pattern = babel.numbers.parse_pattern(pattern)
  File "/home/chris/proj/move/carts/eggs/Babel-2.3.3-py2.7.egg/babel/numbers.py", line 491, in parse_pattern
    if ';' in pattern:
TypeError: argument of type 'NoneType' is not iterable
>>> 
~~~

**Comment by chrisrossi** [comment]
This line looks suspicious:

https://github.com/carlospalol/money/blob/master/src-py2/money/money.py#L266

Should probably pass a key for the currency formats dictionary, not pattern which we've just tested to be None.

**Comment by carlospalol** [comment]
Thanks for catching and reporting this, Chris. Working on a fix and adding new tests.

**Comment by carlospalol** [comment]
Hi Chris, new release 1.3.0 addresses a change in Babel's API introduced in version 2.2. You can check the full [changelog](https://github.com/carlospalol/money/blob/master/CHANGELOG.rst) and upgrade.

Alternatively, you could downgrade Babel to 2.1 and upgrade to Money 1.2.3 (which now checks Babel version).

**Comment by chrisrossi** [comment]
Fantastic, thanks!

Chris
